language: ruby

rvm:
  - 2.4

install:
  - gem install jekyll html-proofer

script:
  - jekyll build --incremental
  - htmlproofer ./_site --only-4xx --check-favicon --check-html

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
