backend:
  name: github
  repo: DevOpsPorto/devopsporto.github.io
  branch: main
  site_domain: hopeful-booth-6a4df2.netlify.com

media_folder: "assets/images"

collections:
  - name: "meetups" # Used in routes, e.g., /admin/collections/meetups
    label: "Meetups" # Used in the UI
    folder: "_includes/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "meetup{{year}}{{month}}{{day}}.html" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
